
language: generic 

sudo: required
services:
  - docker      # Travis will install docker automatically

# Execute these commands before we start the process
before_install:
  - docker build -t rahul9712/dev--docker--docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul9712/dev--docker--docker-react npm run test
#   - docker run rahul9712/dev--docker--docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"         # dockerreact-env.dd7ecjmsmz.us-east-2.elasticbeanstalk.com/
  app: "docker-react"         # https://us-east-2.console.aws.amazon.com/elasticbeanstalk/home?region=us-east-2#/application/overview?applicationName=docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-025262009214"
  bucket_path: "docker-react"     # Same as app name
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
