
language: generic 

sudo: required
services:
  - docker      # Travis will install docker automatically

# Execute these commands before we start the process
before_install:
  - docker build -t rahul9712/dev--docker--docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul9712/dev--docker--docker-react npm run test


# script:
#   - docker run rahul9712/dev--docker--docker-react npm run test -- --coverage
